apiVersion: v1
kind: ConfigMap
metadata:
  name: baseball-dash-config
  namespace: default
data:
  USER_NAME: {{ .Values.userName | quote }}
  THEME_COLOR: {{ .Values.themeColor | quote }}
  SYNC_INTERVAL_MINS: {{ .Values.syncIntervalMins | quote }}