apiVersion: v1
kind: Secret
metadata:
  name: baseball-dash-auth
  namespace: default
type: Opaque
stringData:
  ADMIN_USER: {{ .Values.adminUser | quote }}
  ADMIN_PASSWORD: {{ .Values.adminPassword | quote }}
  FLASK_SECRET_KEY: {{ .Values.flaskSecretKey | quote }}
