apiVersion: v1
kind: Secret
metadata:
  name: baseball-dash-auth-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }} # Best practice: dynamic namespace tracking
type: Opaque
stringData:
  ADMIN_USER: {{ required "An adminUser configuration value is strictly required!" .Values.adminUser | quote }}
  ADMIN_PASSWORD: {{ required "An adminPassword configuration value is strictly required!" .Values.adminPassword | quote }}
  FLASK_SECRET_KEY: {{ required "A flaskSecretKey cryptographic string is strictly required!" .Values.flaskSecretKey | quote }}
