apiVersion: v1
kind: Service
metadata:
  name: baseball-dash-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }} # Best practice: dynamic namespace tracking
spec:
  type: NodePort
  selector:
    app: baseball-dash
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080