apiVersion: v1
kind: Secret
metadata:
  name: baseball-dash-auth
  namespace: default
type: Opaque
stringData:
  ADMIN_USER: "headcoach"
  ADMIN_PASSWORD: "StrikeOutPassword2026"
  FLASK_SECRET_KEY: "prod-crypto-token-salt-string-here"