# Development overrides only.
# This file is not used by default unless you pass it explicitly with -f.

adminUser: "admin"
adminPassword: "1234"
flaskSecretKey: "Gidon"
userName: "Gidon"
themeColor: "dark"
syncIntervalMins: 5
